#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <variant>
#include <utility>

class SkinDatabase {
public:
	class PetsInfo {
	public:
		const char* modelName;
		const char* skinName;
		std::variant<std::int32_t, std::pair<std::int32_t, std::int32_t>> skinCount{ 1 };
	};

	// PetModelName, PetName, PetSkinCount(manual update)
	std::vector<PetsInfo> pets{
		{ "PetAkaliDragon",			"Ossia",					std::make_pair(1, 21)},
		{ "PetAoShin",				"Ao Shin",					std::make_pair(1, 55)},
		{ "PetBallDragon",			"Poggless",					std::make_pair(1, 21)},
		{ "PetBaron",				"Baron Default",			std::make_pair(3, 3)},
		{ "PetBaron",				"Baron Super Squad",		std::make_pair(6, 6)},
		{ "PetBaron",				"Baron Odyssey",			std::make_pair(9, 9)},
		{ "PetBaron",				"Baron Star Guardian",		std::make_pair(12, 12)},
		{ "PetBaron",				"Baron Star Nemesis",		std::make_pair(15, 15)},
		{ "PetBaron",				"Baron Cosmic Scourge",		std::make_pair(18, 18)},
		{ "PetBat",					"Scribble",					std::make_pair(1, 6)},
		{ "PetBellSwayer",			"Bell Swayer",				std::make_pair(1, 23)},
		{ "PetBigKnifeDog",			"Knife Hound",				std::make_pair(1, 18)},
		{ "PetBuglet",				"Flutterbug",				std::make_pair(1, 22)},
		{ "PetBunny",				"Bun Bun",					std::make_pair(1, 48)},
		{ "PetCapybara",			"Capybara",					std::make_pair(1, 2)},
		{ "PetChibiAatrox",			"Chibi Aatrox",				std::make_pair(1, 3)},
		{ "PetChibiAhri",			"Chibi Ahri",				std::make_pair(1, 4)},
		{ "PetChibiAkali",			"Chibi Akali",				std::make_pair(1, 3)},
		{ "PetChibiAmumu",			"Chibi Amumu",				std::make_pair(1, 2)},
		{ "PetChibiAnnie",			"Chibi Annie",				std::make_pair(1, 3)},
		{ "PetChibiAshe",			"Chibi Ashe",				std::make_pair(1, 3)},
		{ "PetChibiBlitzcrank",		"Chibi Blitzcrank",			std::make_pair(1, 3)},
		{ "PetChibiBriar",			"Chibi Briar",				std::make_pair(1, 2)},
		{ "PetChibiCaitlyn",		"Chibi Caitlyn",			std::make_pair(1, 2)},
		{ "PetChibiEkko",			"Chibi Ekko",				std::make_pair(1, 2)},
		{ "PetChibiEzreal",			"Chibi Ezreal",				std::make_pair(1, 3)},
		{ "PetChibiGwen",			"Chibi Gwen",				std::make_pair(1, 4)},
		{ "PetChibiIrelia",			"Chibi Irelia",				std::make_pair(1, 3)},
		{ "PetChibiJanna",			"Chibi Janna",				std::make_pair(1, 2)},
		{ "PetChibiJinx",			"Chibi Jinx",				std::make_pair(1, 2)},
		{ "PetChibiKaisa",			"Chibi Kai'Sa",				std::make_pair(1, 3)},
		{ "PetChibiKatarina",		"Chibi Katarina",			std::make_pair(1, 2)},
		{ "PetChibiKayle",			"Chibi Kayle",				std::make_pair(1, 2)},
		{ "PetChibiLeeSin",			"Chibi Lee Sin",			std::make_pair(1, 3)},
		{ "PetChibiLillia",			"Chibi Lillia",				std::make_pair(1, 2)},
		{ "PetChibiLulu",			"Chibi Lulu",				std::make_pair(1, 2)},
		{ "PetChibiLux",			"Chibi Lux",				std::make_pair(1, 4)},
		{ "PetChibiMalphite",		"Chibi Malphite",			std::make_pair(1, 2)},
		{ "PetChibiMissFortune",	"Chibi MissFortune",		std::make_pair(1, 2)},
		{ "PetChibiMorgana",		"Chibi Morgana",			std::make_pair(1, 3)},
		{ "PetChibiNeeko",			"Chibi Neeko",				std::make_pair(1, 2)},
		{ "PetChibiOrianna",		"Chibi Orianna",			std::make_pair(1, 3)},
		{ "PetChibiRiven",			"Chibi Riven",				std::make_pair(1, 2)},
		{ "PetChibiSeraphine",		"Chibi Seraphine",			std::make_pair(1, 2)},
		{ "PetChibiSett",			"Chibi Sett",				std::make_pair(1, 3)},
		{ "PetChibiSona",			"Chibi Sona",				std::make_pair(1, 2)},
		{ "PetChibiTeemo",			"Chibi Teemo",				std::make_pair(1, 3)},
		{ "PetChibiTristana",		"Chibi Tristana",			std::make_pair(1, 3)},
		{ "PetChibiVi",				"Chibi Vi",					std::make_pair(1, 2)},
		{ "PetChibiYasuo",			"Chibi Yasuo",				std::make_pair(1, 3)},
		{ "PetChibiYone",			"Chibi Yone",				std::make_pair(1, 4)},
		{ "PetChibiYuumi",			"Chibi Yuumi",		        std::make_pair(1, 3)},
		{ "PetChibiYunara",			"Chibi Yunara",		        std::make_pair(1, 2)},
		{ "PetChibiZed",			"Chibi Zed",				std::make_pair(1, 3)},
		{ "PetChibiZoe",			"Chibi Zoe",				std::make_pair(1, 2)},
		{ "PetChickenEggTart",		"Pufflet",					std::make_pair(1, 6)},
		{ "PetChihuahua",			"Blep",						std::make_pair(1, 4)},
		{ "PetChip",		        "Chip",						std::make_pair(1, 6)},
		{ "PetChoncc",				"Choncc",					std::make_pair(1, 51)},
		{ "PetCreepyCat",			"Whisker",					std::make_pair(1, 25)},
		{ "PetCupCake",				"CupCake",					std::make_pair(1, 6)},
		{ "PetDoughCat",			"DoughCat",					std::make_pair(1, 6)},
		{ "PetDowsie",				"Dowsie",					std::make_pair(1, 52)},
		{ "PetDsSquid",				"Squink",					std::make_pair(1, 57)},
		{ "PetDsSwordGuy",			"Abyssia",					std::make_pair(1, 21)},
		{ "PetDsWhale",				"Starmaw",					std::make_pair(1, 21)},
		{ "PetDuckBill",			"Duckbill",					std::make_pair(1, 55)},
		{ "PetElegantDragon",		"Prancie",					std::make_pair(1, 33)},
		{ "PetFairy",				"Nixie",					std::make_pair(1, 24)},
		{ "PetFenroar",				"Fenroar",					std::make_pair(1, 48)},
		{ "PetFishball",			"Fishball",					std::make_pair(1, 6)},
		{ "PetGargoyle",			"Craggle",					std::make_pair(1, 21)},
		{ "PetGemTiger",			"Protector",				std::make_pair(1, 23)},
		{ "PetGhosty",				"Hauntling",				std::make_pair(1, 36)},
		{ "PetGloop",				"Gloop",					std::make_pair(1, 42)},
		{ "PetGriffin",				"Silverwing",				std::make_pair(1, 37)},
		{ "PetGrumpyLion",			"Furyhorn",					std::make_pair(1, 49)},
		{ "PetHamster",		    	"Hamlet",					std::make_pair(1, 5)},
		{ "PetHextechBirb",			"Tocker",					std::make_pair(1, 23)},
		{ "PetHundun",		    	"Hundun",					std::make_pair(1, 33)},
		{ "PetJawDragon",			"Burno",					std::make_pair(1, 33)},
		{ "PetKiko",				"Kiko",						std::make_pair(1, 4)},
		{ "PetKoala",				"Grizzle",					std::make_pair(1, 18)},
		{ "PetKuroShiro",			"Kuro Shiro",				std::make_pair(1, 6)},
		{ "PetLeopardGecko",		"Poptail",					std::make_pair(1, 18)},
		{ "PetMiner",				"Molediver",				std::make_pair(1, 30)},
		{ "PetMiniGolem",			"Runespirit",				std::make_pair(1, 22)},
		{ "PetMinion",				"Minion",					std::make_pair(1, 4)},
		{ "PetMoth",				"Moth",						std::make_pair(1, 6)},
		{ "PetNimbleFoot",			"Nimblefoot",				std::make_pair(1, 21)},
		{ "PetOwl",					"Noctero",					std::make_pair(1, 18)},
		{ "PetPegasus",				"Lightcharger",				std::make_pair(1, 57)},
		{ "PetPenguKnight",			"Featherknight",			std::make_pair(1, 71)},
		{ "PetPixiMander",			"Piximander",				std::make_pair(1, 40)},
		{ "PetPoro",				"Poro",						std::make_pair(1, 11)},
		{ "PetPoroFluft",			"Fluft of Poros",			std::make_pair(1, 1)},
		{ "PetPowderMonkey",		"Powder Monkey",			std::make_pair(1, 4)},
		{ "PetPupDragon",			"Bungo",					std::make_pair(1, 18)},
		{ "PetQiyanaDog",			"QiQi",						std::make_pair(1, 33)},
		{ "PetRazorBeak",			"Raptors",					std::make_pair(1, 18)},
		{ "PetScratch",		    	"Scratch",					std::make_pair(1, 1)},
		{ "PetScuttleCrab",			"Scuttle",					std::make_pair(1, 18)},
		{ "PetSeaAngel",			"Lumie",					std::make_pair(1, 6)},
		{ "PetSennaBunny",			"Melisma",					std::make_pair(1, 40)},
		{ "PetSgCat",				"Dango",					std::make_pair(1, 63)},
		{ "PetSgPig",				"Fuwa",						std::make_pair(1, 31)},
		{ "PetSgShisa",				"Shisa",					std::make_pair(1, 42)},
		{ "PetShark",				"Shork",					std::make_pair(1, 33)},
		{ "PetSmolKnifeDog",		"Knife Pup",		        std::make_pair(1, 33)},
		{ "PetSnake",	        	"Snek",		                std::make_pair(1, 6)},
		{ "PetSpiritFox",			"Hushtail",					std::make_pair(1, 45)},
		{ "PetStyleTwoAhri",		"K/DA Ahri Unbound",		std::make_pair(2, 2)},
		{ "PetStyleTwoDarius",		"God-King Darius Unbound",	std::make_pair(2, 2)},
		{ "PetStyleTwoGaren",		"God-King Garen Unbound",	std::make_pair(2, 2)},
		{ "PetStyleTwoJhin",		"Dark Cosmic Jhin Unbound",	std::make_pair(1, 2)},
		{ "PetStyleTwoJinx",		"Arcane Jinx Unbound",		std::make_pair(3, 3)},
		{ "PetStyleTwoPyke",		"Pyke Unbound",				std::make_pair(2, 2)},
		{ "PetStyleTwoSenna",		"Project Senna Unbound",	std::make_pair(2, 2)},
		{ "PetStyleTwoThresh",		"High Noon Thresh Unbound",	std::make_pair(3, 3)},
		{ "PetStyleTwoVayne",		"Project Vayne Unbound",	std::make_pair(2, 2)},
		{ "PetStyleTwoWarwick",		"Warwick Unbound",	        std::make_pair(1, 1)},
		{ "PetStyleTwoWarwick",		"Arcane Warwick Unbound",	std::make_pair(2, 2)},
		{ "PetStyleTwoYasuo",		"Nightbringer Yasuo",		std::make_pair(2, 2)},
		{ "PetTftAvatar",			"River Sprite",				std::make_pair(1, 29)},
		{ "PetTurtle",				"Paddlemar",				std::make_pair(1, 34)},
		{ "PetUmbra",				"Umbra",					std::make_pair(1, 57)},
		{ "PetVoidEye",				"Khat'Sai",					std::make_pair(1, 18)},
		//Other models
		//{ "TFT_ElderDragon",	        "Elder Dragon"							 }
	};
};
